### ISSUE TITLE
还是有每分钟打印一次日志输出！如下图：

### ISSUE THREAD

**Issue by linhertz** [veighna-global/vnpy_bybit#13]
还是有每分钟打印一次！如下图：

![QQ20240909-224735](https://github.com/user-attachments/assets/f3776387-2bd9-42c7-9d44-3d025e409529)

**Comment by linhertz** [comment]
是每分钟断一次然后重连吗？这也频繁了点儿

**Comment by veighna-global** [comment]
vnpy_bybit需要依赖vnpy_evo作为底层运行，并没有做官方版本的支持
